#!/bin/bash

# curl -X 'GET' \
#  'https://api.foojay.io/disco/v3.0/packages?version=11&distribution=corretto&architecture=x86&archive_type=tar.gz&operating_system=linux' \
#  -H 'accept: application/json'
#curl -L https://api.foojay.io/disco/v3.0/ids/514f8e553fa8693ab74ef35df96f566f/redirect -o /tmp/amazon-corretto-11.0.21.9.1-linux-x86.tar.gz
#tar -xf /tmp/amazon-corretto-11.0.21.9.1-linux-x86.tar.gz
export JAVA_HOME=amazon-corretto-11.0.21.9.1-linux-x86/bin
java --version
./gradlew run